import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  objectsSidebar: [{type: 'autogenerated', dirName: 'objects'}],
  typesSidebar: [{type: 'doc', id: 'globals', label: 'Globals'}, {type: 'autogenerated', dirName: 'types'}],
  moduleSidebar: [
    {type: 'autogenerated', dirName: 'modules'},
    {type: 'link', label: 'sift', href: 'https://cxmeel.github.io/sift/'},
    {type: 'link', label: 'promise', href: 'https://eryn.io/roblox-lua-promise/'},
    {type: 'link', label: 'repr', href: 'https://github.com/Ozzypig/repr/'},
    {type: 'link', label: 'nature2d', href: 'https://jaipack17.github.io/Nature2D/'},
    {type: 'link', label: 'octotree', href: 'https://github.com/Sleitnick/rbxts-octo-tree/'},
    {type: 'link', label: 'signal', href: 'https://sleitnick.github.io/RbxUtil/api/Signal/'},
    {type: 'link', label: 'symbol', href: 'https://sleitnick.github.io/RbxUtil/api/Symbol/'},
    {type: 'link', label: 'trove', href: 'https://sleitnick.github.io/RbxUtil/api/Trove/'},
    {type: 'link', label: 'tableUtil', href: 'https://sleitnick.github.io/RbxUtil/api/TableUtil/'},
  ],
  helpSidebar: [{type: 'autogenerated', dirName: 'help'}],

  // But you can create a sidebar manually
  /*
  documentationSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Documentation',
      items: ['documentation-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
